apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-worker
  template:
    metadata:
      labels:
        app: booking-worker
    spec:
      containers:
      - name: booking-worker
        image: tmydocker1106/my-operator:latest
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
