apiVersion: batch/v1
kind: Job
metadata:
  name: redis-bulk-insert
spec:
  template:
    spec:
      containers:
      - name: redis-cli
        image: redis:7.2
        command: ["sh", "-c"]
        args:
          - |
            for i in $(seq 1 100000); do
              redis-cli -h redis-master.default.svc.cluster.local -a tBoE5Nef5c rpush bookQueue "job-$i"
            done
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Never
  backoffLimit: 1
