apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: "ticketdb"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "yourpassword"
  POSTGRES_HOST_AUTH_METHOD: "trust"