---
# ConfigMap: 存储 PostgreSQL 环境变量
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: "ticketdb"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "yourpassword"
  POSTGRES_HOST_AUTH_METHOD: "trust"
---
# Headless Service: 为 StatefulSet 提供稳定的网络标识
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
# StatefulSet: 使用 volumeClaimTemplates 自动生成 PVC
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: manual-pv  # 使用手动创建的 PV 对应的 StorageClass
---
# PV: 手动定义的 PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-pv
  hostPath:
    path: "/mnt/data/postgres"  # 适用于本地测试；AWS 上应替换为 EBS 卷
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    namespace: default
    name: postgres-storage-postgres-0  # 与 StatefulSet 生成的 PVC 名字匹配