apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-management-service
  template:
    metadata:
      labels:
        app: order-management-service
    spec:
      containers:
        - name: order-management-service
          image: ticket-system/order-management-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50081
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://postgres:5432/ticketdb
            - name: QUARKUS_DATASOURCE_JDBC_DRIVER
              value: org.postgresql.Driver
            - name: QUARKUS_DATASOURCE_USERNAME
              value: postgres
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: yourpassword