---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-ticketdb-cluster
  namespace: cnpg-system
spec:
  instances: 2

  storage:
    size: 1Gi

  bootstrap:
    initdb:
      database: ticketdb

  monitoring:
    enablePodMonitor: true