  service:
    enabled: true
    external:
      enabled: true
    type: LoadBalancer
    ports:
      # -- Port the external HTTP listener is published with.
      http: 80 # 80
      # -- Port the external HTTPS listener is published with.
      https: 443 # 443

  metrics:
    enabled: true
    service:
      enabled: true
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
    serviceMonitor:
      enabled: true
      scrapeInterval: 30s
      additionalLabels: # {}
        release: kube-prometheus-stack
    # prometheusRule:
    #   enabled: true

  controller:
    admissionWebhooks:
      enabled: false