logLevel: 5
prometheus:
  port: 9090
  url: http://prometheus-service.monitoring.svc.cluster.local
rules:
  custom:
  - metricsQuery: rate(<<.Series>>{<<.LabelMatchers>>,container="controller"}[2m])
    name:
      as: nginx_requests
    resources:
      overrides:
        namespace:
          resource: namespace
        pod:
          resource: pod
    seriesQuery: '{__name__="nginx_ingress_controller_nginx_process_requests_total",
      container="controller"}'
  - metricsQuery: sum(rate(nginx_ingress_controller_nginx_process_requests_total{container="controller"}[2m]))
      by (service)
    name:
      as: http_requests_per_second
    resources:
      template: service={{.Resource}}
    seriesQuery: '{__name__="nginx_ingress_controller_nginx_process_requests_total",
      container="controller"}'
  default: false
