# values.yaml

logLevel: 5

prometheus:
  url: http://prometheus-service.monitoring.svc.cluster.local
  port: 9090

config:
  rules:
    version: 1
    rules:
      - seriesQuery: '{__name__="nginx_ingress_controller_nginx_process_requests_total", container="controller"}'
        resources:
          template:
            metadata:
              labels:
                pod: <<pod>>
                namespace: <<namespace>>
        name:
          as: "nginx_requests"
        metricsQuery: 'rate(<<.Series>>{<<.LabelMatchers>>,container="controller"}[2m])'
        scope:
          selector:
            kind: ""
            namespace: "" # 允许跨 ns 使用